redis_host:             localhost
redis_port:             6379
redis_vendor_db:        10
redis_notifications_db: 11
redis_ref_db:           12
mongo_host:             localhost
mongo_port:             27017
mongo_username:         null
mongo_password:         null
flask_host:             localhost
flask_port:             4003
flask_debug:            true
start_year:             2015
source_cve:             https://static.nvd.nist.gov/feeds/xml/cve/
source_cpe:             https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.2.xml
source_cwe:             http://cwe.mitre.org/data/xml/cwec_v2.8.xml.zip
source_capec:           http://capec.mitre.org/data/xml/capec_v2.6.xml
source_via4:            http://www.cve-search.org/feeds/via4.json
