redis_host:                   localhost
redis_port:                   6379
redis_vendor_db:              10
redis_notifications_db:       11
redis_ref_db:                 12
redis_complete_flag:          cveCompleteUpdate
redis_collection_name:        cveupdater
redis_collection_tasks:       tasks
redis_collection_cve:         cves
redis_collection_cpe:         cpe
redis_collection_cwe:         cwe
redis_collection_cpeother:    cpeother
redis_collection_whitelist:   whitelist
redis_collection_blacklist:   blacklist
redis_collection_info:        info
redis_collection_ranking:     ranking
redis_collection_via4:        via4
redis_collection_capec:       capec
mongo_host:                   localhost
mongo_port:                   27017
mongo_username:               null
mongo_password:               null
mongo_db:                     cvedb2
flask_host:                   localhost
flask_port:                   4003
flask_debug:                  true
task_setColUpdate:            setColUpdate
task_setColInfo:              setColInfo
task_insertCVE:               insertCVE
task_updateCVE:               updateCVE
log_use_server:               false
log_use_file:                 true
log_filename:                 updater.log
start_year:                   2016
http_proxy:                   null
cve_file_prefix:              nvdcve-2.0-
cve_file_suffix:              .xml.gz
cve_file_mod:                 modified
cve_file_rec:                 recent
verbose:                      true
source_cve:                   https://static.nvd.nist.gov/feeds/xml/cve/
source_cpe:                   https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.2.xml
source_cwe:                   http://cwe.mitre.org/data/xml/cwec_v2.8.xml.zip
source_capec:                 http://capec.mitre.org/data/xml/capec_v2.6.xml
source_via4:                  http://www.cve-search.org/feeds/via4.json
